### ISSUE TITLE
Error running npm run auto-start-ganache

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#192]
After  `npm install`ing I run, as per instructions:

`npm run auto-start-ganache`

On first try, it errors, a seond try fails immediately. This is on ubuntu. Tracebacks below:

First time error:
```sh
★ npm run auto-start-ganache

> alchemy-client@0.5.2 auto-start-ganache /media/data2/projects/daostack/alchemy
> run-with-ganache --ganache-cmd ganache-cli "npm run migrate-ganache && npm run start"


> alchemy-client@0.5.2 migrate-ganache /media/data2/projects/daostack/alchemy
> npm explore @daostack/arc.js -- npm start migrateContracts && npm explore @daostack/arc.js -- npm start createGenesisDao && node ./scripts/mintGen.js


> @daostack/arc.js@0.0.0-alpha.80 start /media/data2/projects/daostack/alchemy/node_modules/@daostack/arc.js
> nps "migrateContracts"

nps is executing `migrateContracts` : node ../../truffle-core-migrate-without-compile/cli migrate --reset --contracts_build_directory migrated_contracts --without-compile --network ganache
Using network 'ganache' (without compile).

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x0fa8c635495544fe1c6b8accdfc994d4bc847bbda6c6c6291abc60d58ef90ea7
  Migrations: 0x1a6ba4c3194ba8c58e469c5016932115aef79f98
Saving artifacts...
Running migration: 2_deploy_schemes.js
  Running step...
Deploying schemes to ganache
global GEN token does not exist at standard address
global GEN token does not exist in ganache
Creating global GEN token for ganache
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: sender account not recognized
    at Object.InvalidResponse (/media/data2/projects/daostack/alchemy/node_modules/web3/lib/web3/errors.js:38:16)
    at /media/data2/projects/daostack/alchemy/node_modules/web3/lib/web3/requestmanager.js:86:36
    at /media/data2/projects/daostack/alchemy/node_modules/truffle-migrate/index.js:225:11
    at /media/data2/projects/daostack/alchemy/node_modules/truffle-config/node_modules/truffle-provider/wrapper.js:134:9
    at XMLHttpRequest.request.onreadystatechange (/media/data2/projects/daostack/alchemy/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/media/data2/projects/daostack/alchemy/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/media/data2/projects/daostack/alchemy/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/media/data2/projects/daostack/alchemy/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/media/data2/projects/daostack/alchemy/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:185:15)
The script called "migrateContracts" which runs "node ../../truffle-core-migrate-without-compile/cli migrate --reset --contracts_build_directory migrated_contracts --without-compile --network ganache" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @daostack/arc.js@0.0.0-alpha.80 start: `nps "migrateContracts"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @daostack/arc.js@0.0.0-alpha.80 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jelle/.npm/_logs/2018-10-31T11_26_56_988Z-debug.log
npm ERR! weird error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alchemy-client@0.5.2 migrate-ganache: `npm explore @daostack/arc.js -- npm start migrateContracts && npm explore @daostack/arc.js -- npm start createGenesisDao && node ./scripts/mintGen.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alchemy-client@0.5.2 migrate-ganache script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jelle/.npm/_logs/2018-10-31T11_26_57_011Z-debug.log

  Command failed: npm run migrate-ganache && npm run start

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alchemy-client@0.5.2 auto-start-ganache: `run-with-ganache --ganache-cmd ganache-cli "npm run migrate-ganache && npm run start"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alchemy-client@0.5.2 auto-start-ganache script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jelle/.npm/_logs/2018-10-31T11_26_57_051Z-debug.log
```
Second error:
```sh
★ npm run auto-start-ganache

> alchemy-client@0.5.2 auto-start-ganache /media/data2/projects/daostack/alchemy
> run-with-ganache --ganache-cmd ganache-cli "npm run migrate-ganache && npm run start"


  ganache-cli exited early with code 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alchemy-client@0.5.2 auto-start-ganache: `run-with-ganache --ganache-cmd ganache-cli "npm run migrate-ganache && npm run start"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alchemy-client@0.5.2 auto-start-ganache script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jelle/.npm/_logs/2018-10-31T11_47_53_496Z-debug.log
```

**Comment by tibetsprague** [comment]
Honestly I havent been using auto-start-ganache, I will see if its easy to fix otherwise we should just get rid of

**Comment by jellegerbrandy** [comment]
if no one is using it, I'd vote removing :-)
