### ISSUE TITLE
mintGen.ts script isn't working - fix or delete

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#450]
Do we even need it still?
Some of the test accounts already have some gen (e.g. 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1 - thank @jellegerbrandy)...

It seems like a redundant chunk of code so I think we could just delete it.
That being said, I'd appreciate if we could make sure all the test accounts and DAOs created in the migration (is that where it's being created? :) ) also have some eth & gen so it would be easy to play with monetary rewards...

**Comment by A-Zak** [comment]
traceback
```➜  scripts git:(dev) ✗ ts-node mintGen.ts
Error: Cannot find module 'reducers/notifications'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/alex/Development/DAOstack/alchemy/src/lib/util.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/alex/Development/DAOstack/alchemy/src/arc.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)```

**Comment by jellegerbrandy** [comment]
@tibetsprague @brodeur are you guys using this script? If not we remove it.

**Comment by tibetsprague** [comment]
@jellegerbrandy well until more of the test accounts have GEN in the migration, we do need it, or rather, it should be fixed.

**Comment by jellegerbrandy** [comment]
@tibetsprague if you are not using this script let's delete it

**Comment by tibetsprague** [comment]
I guess we can remove. I could imagine wanting it in the future...
